---
skydive_analyzer_docker_extra_env:
skydive_analyzer_docker_image: skydive/skydive
skydive_analyzer_docker_command: analyzer
skydive_analyzer_docker_image_tag:
skydive_etcd_embedded: yes
skydive_etcd_port: 12379
skydive_etcd_scheme: http
skydive_etcd_servers:
skydive_auto_fabric: yes
skydive_fabric_default_interface: eth0
skydive_fabric_tor_name: tor1
skydive_fabric_tor_mtu: 1500
skydive_auth_type:
skydive_basic_auth_file: /var/lib/skydive/skydive.secret

os_auth_url:
os_username:
os_password:
os_tenant_name: admin
os_user_domain_name: Default
os_project_domain_name: Default
os_identity_api_version: 3

# Role of the user created that will be used for the probe
# authentication
skydive_os_service_user_role: admin

skydive_os_auth_url:

skydive_auth_os_tenant_name: skydive
skydive_auth_os_domain_name: Default
skydive_auth_os_domain_id: default
skydive_auth_os_user_role: admin

skydive_deployment_test: yes

skydive_iptables_rules: false

validate_certs: true
