baseurl = "http://redhat-cip.github.io/skydive/"
languageCode = "en-us"
title = "Skydive Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "redhat-cip/skydive"
	description = "Real-time network analyzer."
	copyright = "Released under the Apache license 2.0"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/redhat-cip/skydive"

	version = "1.0.0"
	logo = "images/skydive-logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
			primary = "blue"
			accent  = "white"

  [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "redhat-cip/skydive"


[[menu.main]]
	name   = "Home"
	url    = ""
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Contributing"
	url    = "contributing/"
	weight = 30

	[[menu.main]]
		name   = "Contact"
		url    = "contact/"
		weight = 40

[[menu.main]]
	name   = "License"
	url    = "license"
	weight = 100


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
