baseurl = "//skydive-project.github.io/skydive/"
languageCode = "en-us"
title = "Skydive Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "skydive-project/skydive"
	description = "Real-time network analyzer."
	copyright = "Released under the Apache license 2.0"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/skydive-project/skydive"

	version = "0.9.0"
	logo = "images/skydive-logo.png"
	favicon = "images/skydive-logo-16x16.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
			primary = "light-blue"
			accent  = "white"

  [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "skydive-project/skydive"

[[menu.main]]
	name   = "Home"
	url    = ""
	weight = 0

[[menu.main]]
	name   = "Getting started"
  identifier = "started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
  name = "Installation"
	parent = "started"
	url = "getting-started/install/"
  weight = 100

[[menu.main]]
  name = "Client & WebUI"
	parent = "started"
	url = "getting-started/client/"
  weight = 120

[[menu.main]]
  name = "Openstack"
	parent = "started"
	url = "getting-started/openstack/"
  weight = 300

[[menu.main]]
  name = "Kubernetes"
	parent = "started"
	url = "getting-started/kubernetes/"
  weight = 400

[[menu.main]]
  name = "Docker"
	parent = "started"
	url = "getting-started/docker/"
  weight = 300

[[menu.main]]
  name = "Vagrant"
  parent = "started"
  url = "getting-started/vagrant/"
  weight = 300

[[menu.main]]
	name   = "API"
	identifier = "api"
	url    = "api/"
	weight = 15

[[menu.main]]
	name = "Flows"
	parent = "api"
	url = "api/flows/"
	weight = 1400

[[menu.main]]
	name = "Gremlin language"
	parent = "api"
	url = "api/gremlin/"
	weight = 1300

[[menu.main]]
	name = "Rest"
	parent = "api"
	url = "api/rest/"
	weight = 1500

[[menu.main]]
	name = "Alerts"
	parent = "api"
	url = "api/alerts/"
	weight = 1600

[[menu.main]]
	name   = "Deployment"
	url    = "deployment/"
	weight = 18

[[menu.main]]
	name   = "Architecture"
	url    = "architecture/"
	weight = 20

[[menu.main]]
	name   = "Contributing"
	url    = "contributing/"
	weight = 30

[[menu.main]]
	name   = "Contact"
	url    = "contact/"
	weight = 40

[[menu.main]]
	name   = "License"
	url    = "license"
	weight = 100

[[menu.main]]
	name   = "Use Cases"
	identifier = "usecases"
	url  = "use-cases/"
	weight = 35

[[menu.main]]
	name = "Packet Injector"
	parent = "usecases"
	url = "use-cases/packet-injector/"
	weight = 3500

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
