---
- name: Ensures skydive configuration folder exists
  file:
    path: "{{ skydive_config_file | dirname }}"
    state: directory

- name: Download default config file
  get_url:
    url: https://raw.githubusercontent.com/skydive-project/skydive/{{ skydive_release }}/etc/skydive.yml.default
    dest: "{{ skydive_config_file }}"
    mode: 0644
    force: no
  ignore_errors: yes

- name: Create empty config file is needed
  copy:
    content: ""
    dest: "{{ skydive_config_file }}"
    mode: 0644
    force: no

- name: Set host ID
  yedit:
    src: "{{ skydive_config_file }}"
    key: host_id
    value: "{{ ansible_hostname }}"

- name: Set analyzers list
  yedit:
    src: "{{ skydive_config_file }}"
    key: analyzers
    value: "{{ analyzers.split(',') }}"

- name: Set flow protocol
  yedit:
    src: "{{ skydive_config_file }}"
    key: "flow.protocol"
    value: "{{ skydive_flow_protocol }}"

- name: Define Keystone auth parameters
  yedit:
    src: "{{ skydive_config_file }}"
    edits:
        - key: "auth.analyzer_username"
          value: "{{ os_username }}"
        - key: "auth.analyzer_password"
          value: "{{ os_password }}"
    state: present
  when: skydive_auth_type == "keystone"

- name: Define Openstack parameters
  yedit:
    src: "{{ skydive_config_file }}"
    edits:
        - key: "openstack.auth_url"
          value: "{{ os_auth_url }}"
        - key: "openstack.tenant_name"
          value: "{{ os_tenant_name }}"
        - key: "openstack.domain_name"
          value: "{{ os_domain_name }}"
        - key: "openstack.region_name"
          value: "{{ os_region_name }}"
        - key: "openstack.username"
          value: "{{ os_username }}"
        - key: "openstack.password"
          value: "{{ os_password }}"
        - key: "openstack.endpoint_type"
          value: "{{ os_endpoint_type }}"
    state: present

- name: Define basic auth parameters
  yedit:
    src: "{{ skydive_config_file }}"
    edits:
        - key: "auth.analyzer_username"
          value: "{{ skydive_username }}"
        - key: "auth.analyzer_password"
          value: "{{ skydive_password }}"
    state: present
  when: skydive_auth_type == "basic"

- name: Set extra config vars
  yedit:
    src: "{{ skydive_config_file }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ skydive_extra_config }}"
  when: skydive_extra_config is defined
