apiVersion: v1
description: Skydive is an open source real-time network topology and protocols analyzer.
home: https://skydive-project.github.io/skydive/
icon: https://avatars2.githubusercontent.com/u/19912486?s=400&v=4
keywords:
  - monitoring
  - visualization
  - kubernetes
  - containers
maintainers:
  - name: IBM Research (HRL)
    email: cognetive.support@il.ibm.com
sources:
  - https://github.com/skydive-project/skydive/tree/master/contrib
name: skydive
version: 1.1.2
appVersion: 0.24.0
tillerVersion: ">=2.7.2"
kubeVersion: ">=1.10.0"
