---
skydive_release: v0.17.0
skydive_docker_registry: docker.io
skydive_docker_image: "skydive/skydive"
skydive_docker_image_tag: latest
skydive_config_file: /etc/skydive/skydive.yml
skydive_binary_location: /usr/bin/skydive
skydive_binary_remote_location: https://github.com/skydive-project/skydive/releases/download/{{ skydive_release }}/skydive
skydive_deployment_mode: binary
skydive_etcd_embedded: yes
skydive_analyzer_port: 8082
skydive_agent_port: 8081
skydive_etcd_port: 2379
